// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zailxxhpybcfupenpvsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphaWx4eGhweWJjZnVwZW5wdnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1MDU2MjIsImV4cCI6MjA4ODA4MTYyMn0.ccqH28x-blOqzVdKFj6ydsA871hcAtY4Z2f6R2cCcKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});